---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Docker Deploy DEV

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  push:
    branches:
      - main

env:
  STAGE: dev
  REGION: us-east-2
  REPOSITORY: lfx-clomonitor
  ECR_HOST: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-2.amazonaws.com

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-duration-seconds: 900

      - name: Build Docker Image
        run: |
          echo "Building image with tag: ${ECR_HOST}/${REPOSITORY}:${{github.sha}}"
          docker build --tag ${ECR_HOST}/${REPOSITORY}:${{github.sha}} .

      - name: Tag Docker Image
        run: |
          echo "Tagging image with tag: ${ECR_HOST}/${REPOSITORY}:latest"
          docker image tag ${ECR_HOST}/${REPOSITORY}:${GITHUB_SHA} ${ECR_HOST}/${REPOSITORY}:latest

      - name: Publish Image to ECR
        run: |
          echo "Showing caller identity..."
          aws sts get-caller-identity

          echo "Logging into ECR..."
          aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_HOST}/${REPOSITORY}
          
          # Note: ${REPOSITORY} must exist before running this step (manually need to create it in AWS ECR)

          echo "Publishing image with tag: ${ECR_HOST}/${REPOSITORY}:${{github.sha}}"
          docker push ${ECR_HOST}/${REPOSITORY}:${{github.sha}}
          echo "Publishing image with tag: ${ECR_HOST}/${REPOSITORY}:latest"
          docker push ${ECR_HOST}/${REPOSITORY}:latest
