---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Build Docker Pull Request

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  pull_request:
    branches:
      - main

env:
  STAGE: dev

jobs:
  docker-build-pr:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo "Building image"
          docker build --tag lfx-clomonitor-docker:latest .
