---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Build Docker Pull Request

on:
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
  pull_request:
    branches:
      - main

env:
  STAGE: dev
  REGION: us-east-2
  REPOSITORY: lfx-clomonitor
  ECR_HOST: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-2.amazonaws.com

jobs:
  docker-build-pr:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-duration-seconds: 900

      - name: Build Docker Image
        run: |
          echo "Building image with tag: ${ECR_HOST}/${REPOSITORY}:${{github.sha}}"
          docker build --tag ${ECR_HOST}/${REPOSITORY}:${{github.sha}} .

      - name: Tag Docker Image
        run: |
          echo "Tagging image with tag: ${ECR_HOST}/${REPOSITORY}:latest"
          docker image tag ${ECR_HOST}/${REPOSITORY}:${GITHUB_SHA} ${ECR_HOST}/${REPOSITORY}:latest
